name: 📅 Schedule Workflow Dispatch

on:
  schedule:
    - cron: '0 6 * * *' # every day at 7 AM Madrid (UTC+1/UTC+2)
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 day'

concurrency:
  group: schedule${{ github.event.inputs.date }}
  cancel-in-progress: true

jobs:
  schedule:
    name: 📅 Schedule
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/schedule@v1.3
        with:
          github-token: ${{ secrets.TOKEN }}
          date: ${{ github.event.inputs.date }}
          workflow: 'update.yml'  # Make sure this is the correct workflow file
          timezone: 'Europe/Madrid' # For Madrid time zone
          wait-ms: 45000
