name: 📅 Schedule Workflow Dispatch

on:
  workflow_dispatch:
    
  schedule:
    - cron: "0 7 * * *"

  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        date +%s > lastUpdate
        git config user.name xxs4suk3
        git config user.email bohanjiang09@gmail.com
        git add lastUpdate
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update blog with latest"
        git push origin master
